services:
  postgres:
    image: postgres:18
    container_name: moonlight-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: moonlight
      POSTGRES_PASSWORD: moonlight_dev_password
      POSTGRES_DB: moonlight_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: